spring.application.name=auth-social


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Server Port (Render passes PORT env variable)
server.port=${PORT:8080}

profile.service.url=${PROFILE_SERVICE}

logging.level.org.springframework.web=INFO
logging.level.com.example.social_post=DEBUG


app.cors.allowed-origins=*
